# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Pharmacy Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pharmacy Manager

  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireImage', '~> 4.1'
  pod 'EventsTree'
  pod 'Moya', '~> 14.0'
  pod 'Result', '~> 4.0.0'
  pod 'SwiftGen', '~> 6.0'
  pod "TPKeyboardAvoiding"
  pod 'Kingfisher', '~> 5.0'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'MessageKit'
  pod 'LDSwiftEventSource', '~> 1.2'
  pod 'Firebase/Messaging' 
end
